version: '3.4'

services:
  webui:
    image: ${DOCKER_REGISTRY-}webui
    build:
      context: .
      dockerfile: Dockerfile-local
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=optiroute-db;Port=5432;Database=optiroute-local;Username=optiroute;Password=optiroutedb123!;SSL Mode=Disable;Trust Server Certificate=true; Include Error Detail=true;
    ports:
      - "5000:5000"
    restart: on-failure
    depends_on:
      - "optiroute-db"
  
  optiroute-db:
    ports:
      - '5432:5432'
    container_name: optiroute-db
    environment:
      - POSTGRES_USER=optiroute
      - POSTGRES_PASSWORD=optiroutedb123!
      - POSTGRES_DB=optiroute-local
    volumes:
      - ./volumes/data/db:/var/lib/postgresql/data
    image: postgres:latest
    
    